<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> WASPAS App</title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- Font Awesome if you need it
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
 -->

    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" />
    <!--Replace with your tailwind.css once created-->

    {{-- <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700" rel="stylesheet"> --}}

    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:300,400,500,600,700,800,900" rel="stylesheet" />

    <!-- Animation CSS-->
    <style>
        /* ----------------------------------------------
  * Generated by Animista
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

        .slide-in-bottom {
            -webkit-animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) both;
            animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) both
        }

        .slide-in-bottom-h1 {
            -webkit-animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .5s both;
            animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .5s both
        }

        .slide-in-bottom-subtitle {
            -webkit-animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .75s both;
            animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .75s both
        }

        .fade-in {
            -webkit-animation: fade-in 1.2s cubic-bezier(.39, .575, .565, 1.000) 1s both;
            animation: fade-in 1.2s cubic-bezier(.39, .575, .565, 1.000) 1s both
        }

        .bounce-top-icons {
            -webkit-animation: bounce-top .9s 1s both;
            animation: bounce-top .9s 1s both
        }

        @-webkit-keyframes slide-in-bottom {
            0% {
                -webkit-transform: translateY(1000px);
                transform: translateY(1000px);
                opacity: 0
            }

            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                opacity: 1
            }
        }

        @keyframes slide-in-bottom {
            0% {
                -webkit-transform: translateY(1000px);
                transform: translateY(1000px);
                opacity: 0
            }

            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                opacity: 1
            }
        }

        @-webkit-keyframes bounce-top {
            0% {
                -webkit-transform: translateY(-45px);
                transform: translateY(-45px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in;
                opacity: 1
            }

            24% {
                opacity: 1
            }

            40% {
                -webkit-transform: translateY(-24px);
                transform: translateY(-24px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            65% {
                -webkit-transform: translateY(-12px);
                transform: translateY(-12px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            82% {
                -webkit-transform: translateY(-6px);
                transform: translateY(-6px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            93% {
                -webkit-transform: translateY(-4px);
                transform: translateY(-4px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            25%,
            55%,
            75%,
            87% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }

            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out;
                opacity: 1
            }
        }

        @keyframes bounce-top {
            0% {
                -webkit-transform: translateY(-45px);
                transform: translateY(-45px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in;
                opacity: 1
            }

            24% {
                opacity: 1
            }

            40% {
                -webkit-transform: translateY(-24px);
                transform: translateY(-24px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            65% {
                -webkit-transform: translateY(-12px);
                transform: translateY(-12px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            82% {
                -webkit-transform: translateY(-6px);
                transform: translateY(-6px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            93% {
                -webkit-transform: translateY(-4px);
                transform: translateY(-4px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            25%,
            55%,
            75%,
            87% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }

            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out;
                opacity: 1
            }
        }

        @-webkit-keyframes fade-in {
            0% {
                opacity: 0
            }

            100% {
                opacity: 1
            }
        }

        @keyframes fade-in {
            0% {
                opacity: 0
            }

            100% {
                opacity: 1
            }
        }
    </style>

</head>

<body class="leading-normal tracking-normal text-gray-900" style="font-family: 'Figtree', sans-serif;">

    <div class="h-screen pb-14 bg-right bg-cover" style="background-image:url('bg.svg');">
        <!--Nav-->
        <div class="w-full container mx-auto p-6">

            <div class="w-full flex items-center justify-between">
                <a class="flex items-center text-indigo-400 no-underline hover:no-underline font-bold text-2xl lg:text-4xl sm:mr-auto mr-20"
                    href="#">
                    <x-waspas-logo class="block h-9 w-auto fill-current text-gray-800" />
                    <p class="mx-5 text-2xl font-bold text-gray-800"> WASPAS </p>
                </a>

                <div class="flex w-1/2 justify-end content-center">
                    @auth
                    @else
                        <a href="{{ route('login') }}">
                            <x-button icon="login" green label="Login" class="w-full" />
                        </a>
                    @endauth
                    <div class="w-5"></div>
                    @auth
                        <a href="{{ route('dashboard') }}">
                            <x-button icon="home" label="Dashboard" dark class="h-10" />
                        </a>
                    @else
                        <a href="{{ route('register') }}" class="sm:visible invisible">
                            <x-button icon="plus" outline green label="Register" />
                        </a>
                    @endauth
                </div>

            </div>

        </div>

        <!--Main-->
        <div class="container w-full mt-4 pt-24 md:pt-10 px-6 mx-auto flex flex-wrap flex-col md:flex-row items-center">

            <!--Left Col-->
            <div class="flex flex-col w-full xl:w-2/5 justify-center lg:items-start overflow-y-hidden">
                <h1
                    class="my-4 text-3xl md:text-4xl font-bold leading-tight text-center md:text-left slide-in-bottom-h1">
                    Temukan <span class="text-green-600">solusi ideal</span> dari masalah Anda.</h1>
                <p class="leading-normal text-base md:text-xl mb-8 text-center md:text-left slide-in-bottom-subtitle">
                    WASPAS App adalah sistem pendukung keputusan yang menerapkan metode WASPAS. Sistem akan memberikan
                    hasil analisis beserta solusi ideal dari beragam situasi berdasarkan kriteria dan bobot kriteria
                    yang dimasukkan.</p>


                <div class="flex w-full justify-center md:justify-start pb-24 lg:pb-0 fade-in">
                    <a href="{{ route('dashboard') }}">
                        <x-button xl right-icon="arrow-right" green label="Mulai buat keputusan!"
                            class="h-12 pr-4 bounce-top-icons" />
                    </a>
                    {{-- <img src="Play Store.svg" class="h-12 bounce-top-icons"> --}}
                </div>

            </div>

            <!--Right Col-->
            <div class="w-full h-full xl:w-3/5 overflow-y-hidden">
                <img class="mx-auto lg:mr-0 slide-in-bottom" src="welcome.svg">
            </div>

            <!--WASPAS-->
            <section id="waspas" class="w-full my-10">
                <div class="w-full flex flex-col gap-5 container mx-auto items-center m-10 mt-20">
                    {{-- <div class="w-full bg-green-500 p-2 rounded"> --}}
                    <p
                        class="w-full left-[69px] top-[1073px] text-center text-gray-800 text-lg md:text-xl font-extrabold">
                        Apa itu Metode WASPAS?</p>
                    {{-- </div> --}}
                    <p
                        class="w-[1302px] left-[69px] top-[1148px] text-justify text-gray-800 text-base font-medium leading-7 md:leading-8">
                        WASPAS App menggunakan Weighted Aggregated Sum Product Assesment (WASPAS) sebagai metode
                        perhitungan dalam pemilihan keputusan. Konsep perhitungan pada metode WASPAS, yaitu
                        menormalisasi matriks, menghitung nilai normalisasi berdasarkan bobot, dan mengurutkan
                        alternatif berdasarkan nilai normalisasi.</p>

                    <!--Step 1-->
                    <div class="w-full mt-2">
                        <div class="flex">
                            <div
                                class="w-[77px] h-[77px] px-6 py-2 left-[69px] top-[1354px]  bg-green-600 rounded justify-center items-center gap-2.5 inline-flex">
                                <div class="grow shrink basis-0 text-center text-white text-base font-medium">1</div>
                            </div>
                            <div
                                class="w-96 h-[77px] mx-1 px-8 py-2 left-[162px] top-[1354px]  bg-green-600 rounded justify-start items-center gap-2.5 flex-1">
                                <div class="grow shrink basis-0 text-left text-white text-base font-medium">Membuat
                                    Matriks Keputusan</div>
                            </div>
                        </div>
                        <div
                            class="w-[1302px] left-[69px] top-[1462px] mt-2 text-left text-gray-800 text-base font-medium leading-7 md:leading-8">
                            Langkah pertama adalah memasukkan nilai-nilai alternatif ke dalam matriks keputusan.</div>
                    </div>

                    <div class="w-1/2 md:w-96 left-0 top-0 bg-yellow-500 rounded">
                        <img src="{{ asset('/images/matrix.png') }}" />
                    </div>

                    <!--Step 2-->
                    <div class="w-full mt-2">
                        <div class="flex">
                            <div
                                class="w-[77px] h-[77px] px-6 py-2 left-[69px] top-[1354px]  bg-green-600 rounded justify-center items-center gap-2.5 inline-flex">
                                <div class="grow shrink basis-0 text-center text-white text-base font-medium">2</div>
                            </div>
                            <div
                                class="w-96 h-[77px] mx-1 px-8 py-2 left-[162px] top-[1354px]  bg-green-600 rounded justify-start items-center gap-2.5 flex-1">
                                <div class="grow shrink basis-0 text-left text-white text-base font-medium">Membuat
                                    Matriks Normalisasi</div>
                            </div>
                        </div>
                        <div
                            class="w-[1302px] left-[69px] top-[1462px] mt-2 text-left text-gray-800 text-base font-medium leading-7 md:leading-8">
                            Selanjutnya, menyusun matriks normalisasi berdasarkan matriks keputusan yang telah dibuat.
                            Nilai matriks keputusan yang ada dimasukkan ke dalam rumus normalisasi yang berbeda
                            tergantung jenis kriteria.</div>
                    </div>

                    <div class="flex flex-row gap-7">
                        <div>
                            <div
                                class="w-[510px] left-[188px] top-[2123px]  text-center text-gray-800 text-[20px] font-medium leading-8">
                                Jika kriteria merupakan benefit</div>
                            <div class="w-full md:w-96 left-0 top-0  bg-yellow-500 rounded">
                                <img src="{{ asset('/images/benefit.png') }}" />
                            </div>
                        </div>
                        <div>
                            <div
                                class="w-[510px] left-[743px] top-[2123px]  text-center text-gray-800 text-[20px] font-medium leading-8">
                                Jika kriteria merupakan cost</div>
                            <div class="w-full md:w-96 left-0 top-0  bg-yellow-500 rounded">
                                <img src="{{ asset('/images/cost.png') }}" />
                            </div>
                        </div>
                    </div>

                    <div
                        class="w-full left-[69px] top-[2994px] text-justify text-gray-800 text-[28px] font-medium leading-8">
                        Keterangan<br />X̄ij = nilai matriks keputusan<br />MaxiXij = nilai maksimum pada kriteria
                        (kolom)<br>MiniXij = nilai minimum pada kriteria (kolom)</div>

                    <!--Step 3-->
                    <div class="w-full mt-2">
                        <div class="flex">
                            <div
                                class="w-[77px] h-[77px] px-6 py-2 left-[69px] top-[1354px]  bg-green-600 rounded justify-center items-center gap-2.5 inline-flex">
                                <div class="grow shrink basis-0 text-center text-white text-base font-medium">3</div>
                            </div>
                            <div
                                class="w-96 h-[77px] mx-1 px-8 py-2 left-[162px] top-[1354px]  bg-green-600 rounded justify-start items-center gap-2.5 flex-1">
                                <div class="grow shrink basis-0 text-left text-white text-base font-medium">Menghitung
                                    Nilai Normalisasi Alternatif</div>
                            </div>
                        </div>
                        <div
                            class="w-[1302px] left-[69px] top-[1462px] mt-2 text-left text-gray-800 text-base font-medium leading-7 md:leading-8">
                            Setelah menyusun matriks ternormalisasi, nilai-nilai pada matriks ini akan dihitung
                            menggunakan rumus WASPAS untuk mencari nilai normalisasi alternatif. Hasil nilai normalisasi
                            alternatif menentukan peringkat akhir dari masing-masing alternatif dan menemukan solusi
                            ideal dari permasalahan.</div>
                    </div>

                    <div class="w-2/3 md:w-96 px-3 left-0 top-0 bg-yellow-500 rounded">
                        <img src="{{ asset('/images/q.png') }}" />
                    </div>

                    <div
                        class="w-full left-[69px] top-[2994px] text-justify text-gray-800 text-[28px] font-medium leading-8">
                        Keterangan<br />0,5 merupakan ketetapan<br />Q = nilai normalisasi alternatif<br />X̄ij = nilai
                        matriks ternormalisasi<br />wj = nilai bobot kriteria</div>

            </section>
            <!--END-->

            <!--Footer-->
            <div class="w-full pt-2 pb-6 text-sm text-center md:text-left fade-in">
                <a class="text-gray-500 no-underline hover:no-underline" href="#">&copy; WASPAS App</a>
            </div>
        </div>


    </div>


    <!-- jQuery if you need it
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  -->

</body>

</html>
